### PR TITLE
Fix proxy-pass url

### PR DESCRIPTION
**Pull request by jukefr**
Causing issues with npm registry (and probably more) See https://github.com/go-gitea/gitea/issues/21407 and specifically https://github.com/go-gitea/gitea/issues/21407#issuecomment-1420975465

## Problem

See https://github.com/YunoHost-Apps/gitea_ynh/issues/73

## Solution

Removing the slash

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by jukefr** [comment]
!testme

**Comment by Josue-T** [comment]
!testme

**Comment by jukefr** [comment]
not sure why subpath install seems to make this go wrong i dont know nginx well enough so i'll let people who do handle this
i know for subdomain install this seems to work fine

**Comment by ericgaspar** [comment]
!testme

**Comment by Josue-T** [comment]
Closing as #113 should fix it

**Pull request closed without merging**
