### PR TITLE
Add correct user to ssh.app group so multi-instance works.

### PR DESCRIPTION
**Pull request by ndarilek**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ndarilek** [comment]
!testme

**Comment by ndarilek** [comment]
This should be ready to merge--not sure what if anything I need to do on my end. Thanks!

**Review by Josue-T — APPROVED** [review]

**Comment by Josue-T** [comment]
!testme

**Comment by Josue-T** [comment]
!testme

**Comment by ndarilek** [comment]
How would I go about getting this merged?

Thanks.

**Pull request merged**
